
Microsoft Visual Studio Solution File, Format Version 9.00
# Visual Studio 2005
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "MakeFile", "MakeFile\MakeFile.vcproj", "{FBC91A8F-8C07-4822-B133-BF59D6862598}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Debug|Mixed Platforms = Debug|Mixed Platforms
		Debug|Win32 = Debug|Win32
		Release|Any CPU = Release|Any CPU
		Release|Mixed Platforms = Release|Mixed Platforms
		Release|Win32 = Release|Win32
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{FBC91A8F-8C07-4822-B133-BF59D6862598}.Debug|Any CPU.ActiveCfg = Debug|Win32
		{FBC91A8F-8C07-4822-B133-BF59D6862598}.Debug|Mixed Platforms.ActiveCfg = Debug|Win32
		{FBC91A8F-8C07-4822-B133-BF59D6862598}.Debug|Mixed Platforms.Build.0 = Debug|Win32
		{FBC91A8F-8C07-4822-B133-BF59D6862598}.Debug|Win32.ActiveCfg = Debug|Win32
		{FBC91A8F-8C07-4822-B133-BF59D6862598}.Debug|Win32.Build.0 = Debug|Win32
		{FBC91A8F-8C07-4822-B133-BF59D6862598}.Release|Any CPU.ActiveCfg = Release|Win32
		{FBC91A8F-8C07-4822-B133-BF59D6862598}.Release|Mixed Platforms.ActiveCfg = Release|Win32
		{FBC91A8F-8C07-4822-B133-BF59D6862598}.Release|Mixed Platforms.Build.0 = Release|Win32
		{FBC91A8F-8C07-4822-B133-BF59D6862598}.Release|Win32.ActiveCfg = Release|Win32
		{FBC91A8F-8C07-4822-B133-BF59D6862598}.Release|Win32.Build.0 = Release|Win32
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
